title: Hyla Repository
description: Hyla homepage for all PJATK-related stuff!
theme: just-the-docs

color_scheme: dark
url: https://mhyla.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  labs:
    output: true
    permalink: :slug/