title: Hyla Repository
description: Hyla homepage for all PJATK-related stuff!
repository: mhyla-pj/mhyla-pj.github.io # for github-metadata
theme: "just-the-docs"
permalink: pretty

math: mathjax

color_scheme: dark
url: https://mhyla.com

aux_links:
  Stara strona: http://users.pja.edu.pl/~mhyla/

collections:
  labs:
    output: true
    permalink: :slug/
  exercises:
    output: true
    permalink: :slug/
  announcements:
    output: true
    permalink: :slug/

callouts:
  warning: 
    title: Uwaga!
    color: red
  important:
    title: Wa≈ºna uwaga
    color: blue

mermaid: 
  version: 9.3.0
  
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false



favicon_ico: /assets/favicon.ico