title: Hyla Repository
description: Hyla homepage for all PJATK-related stuff!
theme: just-the-docs

color_scheme: dark
url: https://mhyla.com

aux_links:
  Stara strona: http://users.pja.edu.pl/~mhyla/

collections:
  labs:
    output: true
    permalink: :slug/
  exercises:
    output: true
    permalink: :slug/
  announcements:
    output: true
    permalink: :slug/

mermaid: 
  version: 9.3.0
  
search.heading_level: 2